spring.application.name=PP_GROUP_02_SPRING_MINI_PROJECT

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_mini_project_db
spring.datasource.username=postgres
spring.datasource.password=240904
